// src/app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { JobsProvider } from "../hooks/useJobs";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "ACTS - Audio Recording & Creative Transcription Information System",
    description: "Transcribe and generate content from audio files and YouTube video powered by Tim Digital Garuda TV",
    icon: "/favicon.ico",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          antialiased 
          flex 
          flex-col 
          min-h-screen 
          bg-gray-50 
          text-gray-900
        `}
            >
                {/* Wrap the entire app with JobsProvider */}
                <JobsProvider>{children}</JobsProvider>

                {/* Global Footer */}
                <footer className="w-full bg-slate-700 py-6 mt-8">
                    <div className="container mx-auto text-center px-4">
                        {/* Powered by Section */}
                        <p className="text-xs text-gray-300">Powered by:</p>
                        <a
                            href="https://garuda.tv"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="inline-block mt-2 mb-3"
                        >
                            <img
                                src="https://garuda.tv/wp-content/uploads/2024/12/Logo_GarudaTV_Merah_Flat_2025.svg"
                                alt="Logo GarudaTV"
                                className="mx-auto w-auto h-12 p-2"
                            />
                        </a>

                        {/* Disclaimer */}
                        <p className="text-sm text-gray-300 max-w-2xl mx-auto leading-relaxed">
                            Disclaimer: Always verify the information generated by this tool with official sources before making any publication.
                            The generated content is for informational & educational purposes only.
                        </p>

                        {/* Horizontal Divider */}
                        <hr className="border-gray-500 my-4" />

                        {/* Copyright Notice */}
                        <p className="text-xs text-gray-400 mt-4">
                            © {new Date().getFullYear()} Divisi Digital Garuda TV. All rights reserved.
                        </p>
                    </div>
                </footer>
            </body>
        </html>
    );
}