"""Add config column to content_generation table

Revision ID: 229a2bc95ee1
Revises: bec4fdaf2407
Create Date: 2025-02-17 18:46:50.114125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '229a2bc95ee1'
down_revision: Union[str, None] = 'bec4fdaf2407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
