"""Added content generation table

Revision ID: 51e3f411a509
Revises: 
Create Date: 2025-02-14 02:20:05.378942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e3f411a509'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###
op.execute("DROP INDEX IF EXISTS ix_content_generation_id")
op.create_index("ix_content_generation_id", "content_generation", [
                "id"], unique=False)    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_generation_id'),
                  table_name='content_generation')
    # ### end Alembic commands ###
