"""Added title field and improved history tracking

Revision ID: a10439a8b965
Revises: 51e3f411a509
Create Date: 2025-02-14 09:36:07.564195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a10439a8b965'
down_revision: Union[str, None] = '51e3f411a509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_generation', sa.Column('title', sa.String(), nullable=True))
    op.add_column('transcription_history', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcription_history', 'title')
    op.drop_column('content_generation', 'title')
    # ### end Alembic commands ###
