"""AGAIN Add config column to content_generation table

Revision ID: a986abf6aceb
Revises: 229a2bc95ee1
Create Date: 2025-02-17 18:52:15.931234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a986abf6aceb'
down_revision: Union[str, None] = '229a2bc95ee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
