"""Add config column to content_generation table

Revision ID: bec4fdaf2407
Revises: a10439a8b965
Create Date: 2025-02-17 18:31:59.430952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bec4fdaf2407'
down_revision: Union[str, None] = 'a10439a8b965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_generation', sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_generation', 'config')
    # ### end Alembic commands ###
